services:
  your-money:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    image: your-money
    container_name: your-money-app
    user: "root"
    tty: true
    volumes:
      - .:/var/www
    networks:
      - laravel_app
  nginx:
    image: nginx:alpine
    container_name: your-money-nginx
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
  mysql:
    image: mysql:5.7
    container_name: your-money-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
    networks:
      - laravel_app
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql
networks:
  laravel_app:
    driver: bridge